name: Test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: write
  checks: write

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: build